name: Register repository
on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  register-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Register new repository
        run: |
          python -m pip install pyyaml requests
          python .github/workflows/register_repo.py

      - name: Pushing up-to-date config file
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const payload = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'))
            const repo_and_campaign = payload.issue.body.split('/add-repo')
            const issue_reply = `👋 Added  ${repo_and_campaign} to the configuration file!`
            // Send a reply message to the issue
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issue_reply
            })


      

      